// Fictional voices based on workshop registration and follow-up replies.
// Rough counts are rounded and overlap.
export const crowd = {
  snapshot: "October 6, 2026",
  people: [
    {
      id: "pip",
      portrait: "sprig",
      name: "Green",
      label: "Finding an idea",
      count: 65,
      color: "#e9f2df",
      blurb: "I'm still choosing my idea. I'm excited to discover what an agent could do and get inspiration from other people's projects. I worry about picking something so broad that I never finish it. Help me find one small problem I care enough about to keep exploring.",
    },
    {
      id: "moxie",
      portrait: "patch",
      name: "Purple",
      label: "Career momentum",
      count: 35,
      color: "#f0eafa",
      blurb: "I know I want a useful project for a career conversation, though the topic is still open. I'm excited to build something worth showing and meet people who can give me feedback. I worry about ending up with a generic demo while interviews, classes and the presentation compete for my time.",
    },
    {
      id: "clover",
      portrait: "ember",
      name: "Orange",
      label: "Everyday problems",
      count: 35,
      color: "#fff0db",
      blurb: "I have an everyday annoyance in mind, like choosing a café, planning a day or keeping records up to date. I'm excited to make something I would use myself. I worry about wrong details and an idea that grows into an assistant for everything. One task made easier would be a good start.",
    },
    {
      id: "rivet",
      portrait: "socket",
      name: "Yellow",
      label: "Workflows that last",
      count: 35,
      color: "#faf0cd",
      blurb: "I have a work process or a project already in motion. I'm excited to finish a useful part that saves repeated effort. I worry about missing information, hidden mistakes and who approves the next action. Help me make a small promise I can keep when another person starts relying on the result.",
    },
    {
      id: "quill",
      portrait: "chorus",
      name: "Pink",
      label: "Research questions",
      count: 30,
      color: "#f9e7eb",
      blurb: "I have a field or a research question in mind, but the experiment may still be open. I'm excited to explore simulations or connect evidence across a collection of material. I worry that a convincing story could outrun the evidence. I want a result I can inspect and a clearer question to pursue.",
    },
    {
      id: "harbor",
      portrait: "nimbus",
      name: "Blue",
      label: "Care and access",
      count: 25,
      color: "#e4f1f6",
      blurb: "I know whom I want to help: someone waiting for care, learning support or a service they struggle to access. My idea might still be a large ambition. I'm excited by the possibility of making help easier to get. I worry about privacy, unfairness and mistakes, so people need a way to question the result.",
    },
  ],
} as const;
