// Public composite voices adapted from the private October 1 registration snapshot.
// Counts describe form responses, not accepted students or attendance.
export const crowd = {
  responses: 133,
  snapshot: "October 1, 2026",
  people: [
    {
      id: "ember",
      name: "Ember",
      label: "API tinkerers",
      count: 39,
      color: "#e8a274",
      intro: "My first model call works. Once I add tools and state, I want to understand how the whole agent fits together.",
      excites: "Turning an API experiment into something another person can use.",
      worries: "Losing the thread when the system grows or an API fails.",
      leaveWith: "A useful agent I can explain from the first request to the final result.",
    },
    {
      id: "patch",
      name: "Patch",
      label: "Copilot builders",
      count: 37,
      color: "#d9bee7",
      intro: "A coding assistant can help me build fast. I want to understand the decisions behind what it built.",
      excites: "Making a project of my own and seeing what other builders try.",
      worries: "Having a working demo I cannot explain when someone asks how it works.",
      leaveWith: "Confidence showing what I changed, why I changed it, and what happened.",
    },
    {
      id: "sprig",
      name: "Sprig",
      label: "Curious explorers",
      count: 16,
      color: "#b8d2a3",
      intro: "I use AI through chat. Show me the moment it takes an action, and I can start to imagine building my own.",
      excites: "Watching a small tool call become a result I can actually use.",
      worries: "Getting lost when the vocabulary moves faster than the example.",
      leaveWith: "A first working agent and a clear idea of what to learn next.",
    },
    {
      id: "nimbus",
      name: "Nimbus",
      label: "Workflow dreamers",
      count: 15,
      color: "#b8e1e7",
      intro: "I have a list of tasks I would love to hand off. I need help choosing one I can finish.",
      excites: "Turning an everyday routine into a useful application.",
      worries: "Starting too big and spending my time on setup instead of the idea.",
      leaveWith: "One purposeful project I can keep improving after class.",
    },
    {
      id: "socket",
      name: "Socket",
      label: "Tool connectors",
      count: 14,
      color: "#f0d192",
      intro: "I have connected tools with MCP. Now I want to see what makes them part of a complete agent.",
      excites: "Following a tool result through the next decision in a real workflow.",
      worries: "Knowing the pieces without understanding how they work together.",
      leaveWith: "A complete system whose design choices I can explain.",
    },
    {
      id: "chorus",
      name: "Chorus",
      label: "System orchestrators",
      count: 12,
      color: "#e8b3c6",
      intro: "I have had agents working together. I want to know when the extra coordination is worth it.",
      excites: "Looking closely at a handoff and seeing what it improves.",
      worries: "Adding another agent because it sounds impressive, even when it makes the task harder.",
      leaveWith: "A way to judge when several agents help and when one is enough.",
    },
  ],
} as const;
